/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    // colors: {
    //   'ground' :'#92400e',
    //   'rock' :'#9ca3af',
    //   'ghost' :'#f5f5f4',
    //   'electric' :'#facc15',
    //   'bug' :'#365314',
    //   'poison' :'#a21caf',
    //   'normal' :'#e2e8f0',
    //   'fair':'#f9a8d4',
    //   'fire' :'#ff5436c7',
    //   'grass' :'#b2f8b0c7',
    //   'water' :'#3b82f6',
    //   'fighting' :'#756b49c7',
    //   'psychic' :'#351e38c7',
    //   'ice' :'#8eb3ddc7',
    //   'dragon' :'#ca8b14c7',
    //   'dark' :'#2b2a2ac7',
    //   'steel' :'#dbdbdbc7',
    //   'flying' :'#879c7bc7',
    // },
  },

  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [ "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",],
  },
}

